import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Header } from '@/components/header'
import { Footer } from '@/components/footer'
import { ContentCard } from '@/components/cotent_card'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Sstoshi's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className="">
        <div className={styles.center}>
          <Image
            className={styles.center}
            src="/mainvisual_seaClouds.jpg"
            alt="mainvisual"
            width={1920}
            height={1080}
            priority
          />
        </div>

        <section className="l-addMaxWidth_x_center_y_column" id="area_profile">
          <div className="l-x_center_y_column">
            <h1 className="p-sectionTitle_margin p-sectionTitle_underline"> Profile</h1>
            <div className="l-x_center_y_center">
              <img className="p-roundUpImage" src="/profile_水玉模様.jpg" alt="プロフィール写真"/>
              <div>
                <h2 className="p-contentTitle_margin">SATOSHI KAGEYAMA</h2>
                <p>マルチメディアデザイナー</p>
                <p>小さいことの積み重ねが、とんでもないところに行くただひとつの道</p>
                <p>明日が今日よりも良き日であるように、今 "　　" に何ができるのか？</p>
              </div>
            </div>
          </div>
        </section>

        <section className="l-addMaxWidth_x_center_y_column" id="area_work">
          <div className="l-x_center_y_column">
            <h1 className="p-sectionTitle_margin p-sectionTitle_underline">Work</h1>
            <ul className="l-grid_x_25rem-1fr">
              <ContentCard
                imgSrc="img/photo_coffee.jpg" 
                contentTitle="Paper" 
                text="紙媒体のポートフォリをまとめています"
              />
              <ContentCard
                imgSrc="img/photo_ diving.jpg" 
                contentTitle="Web" 
                text="webブラウザのポートフォリをまとめています"
              />
            </ul>  
          </div>
        </section>

      </main>
      <Footer />
    </>
  )
}
