name: CI deploy next.js

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      HOSTNAME: ${{ secrets.HOSTNAME }}
      USERNAME: ${{ secrets.USERNAME }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      PORT: ${{ secrets.PORT }}
      FULLPATH: ${{ secrets.FULLPATH }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.16

      - name: Install NPM packages
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: $HOSTNAME
          username: $USERNAME
          password: $SSH_PRIVATE_KEY
          port: $PORT
          local-dir: ./out/
          server-dir: $FULLPATH
          protocol: ftps
